---
- hosts: localhost
  gather_facts: yes
  pre_tasks:
    - name: Limit to Archlinux
      fail:
        msg: "{{ ansible_distribution }} is not supported with this tag."
      when: (ansible_distribution != "Archlinux")

  roles:
      - role: zsh
      - role: nvim
      - role: alacritty
      - role: emacs
      - role: i3
