---
- name: install zsh
  pacman:
      name: zsh
  become: yes

- name: copy .zshrc file
  copy:
      src: zshrc
      dest: ~/.zshrc
  notify:
      - upgrade zsh
  tags:
      - zsh-upgrade

- name: copy .npmrc file
  copy:
      src: npmrc
      dest: ~/.npmrc
