---
- name: install rofi
  pacman:
      name: rofi
  become: yes

- name: create rofi config dir
  file:
      path: ~/.config/rofi/
      state: directory

- name: copy rofi config file
  copy:
      src: .
      dest: ~/.config/rofi/
